---
# Apex OS — Calamares installer (instalacija na disk s USB live sustava)

modules-search: [ local ]

instances:
- id:       rootfs
  module:   unpackfs
  config:   unpackfs.conf
- id:       unpackfs
  module:   unpackfs
  config:   unpackfs.conf

sequence:
- show:
  - welcome
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - filesystem
  - unpackfs
  - users
  - services-systemd
  - bootloader
- show:
  - finished

branding: default
prompt-install: true
dont-chroot: false
