# Apex OS — dopušta jače pojačavanje zvuka (PipeWire / ALSA)
monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.*" }
      { node.name = "~alsa_input.*" }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mix = true
        api.alsa.ignore-dB = true
      }
    }
  }
]
